export enum Category{

}

export type Hack = {
    name: string,
    category : string,
    description: string,
}

export const Hacks : Hack[] = [
    {name:"Aimbot", category:"Combat", description: "Automatically aims at nearby entities."},
    {name:"AntiCactus", category:"Misc", description: "Prevents damage from cacti."},
    {name:"AntiHunger", category:"Misc", description: "Reduces hunger depletion rate."},
    {name:"AntiInvis", category:"Combat", description: "Reveals invisible players and entities."},
    {name:"AntiKnockback", category:"Combat", description: "Reduces or eliminates knockback from attacks and explosions."},
    {name:"AutoEat", category:"Misc", description: "Automatically consumes food when hunger is low."},
    {name:"AutoFarm", category:"World", description: "Automatically harvests and replants crops in range."},
    {name:"AutoFish", category:"Misc", description: "Automates fishing by detecting and reeling in catches."},
    {name:"AutoOminousBottle", category:"Misc", description: "Automatically uses ominous bottles."},
    {name:"AutoRespawn", category:"Combat", description: "Instantly respawns upon death."},
    {name:"AutoShear", category:"Misc", description: "Automatically shears nearby sheep."},
    {name:"AutoSign", category:"World", description: "Automatically writes text on placed signs."},
    {name:"AutoSoup", category:"Combat", description: "Automatically consumes soup for health regeneration."},
    {name:"AutoTotem", category:"Combat", description: "Automatically equips totems of undying."},
    {name:"AutoWalk", category:"Misc", description: "Automatically walks in a specified direction."},
    {name:"BedAura", category:"Combat", description: "Automatically breaks nearby beds."},
    {name:"BlockESP", category:"Render", description: "Highlights specific blocks through walls."},
    {name:"BowAimbot", category:"Combat", description: "Automatically aims based on projectile velocity."},
    {name:"Breadcrumbs", category:"Render", description: "Renders a trail showing your movement path."},
    {name:"ChestESP", category:"Render", description: "Highlights storage containers through walls."},
    {name:"ClickTP", category:"Movement", description: "Teleport to where you click."},
    {name:"Criticals", category:"Combat", description: "Forces critical hits on every attack."},
    {name:"CrystalAura", category:"Combat", description: "Automatically places and detonates end crystals."},
    {name:"DiscordRPC", category:"Misc", description: "Displays Aoba Client status on Discord rich presence."},
    {name:"EntityControl", category:"Movement", description: "Take control of ridden entities."},
    {name:"EntityESP", category:"Render", description: "Highlights all entities through walls."},
    {name:"EXPThrower", category:"Misc", description: "Automatically throws experience bottles."},
    {name:"FakePlayer", category:"Misc", description: "Spawns a client-side fake player entity."},
    {name:"FastBreak", category:"Misc", description: "Increases block breaking speed."},
    {name:"FastLadder", category:"Movement", description: "Increases ladder climbing speed."},
    {name:"FastPlace", category:"Misc", description: "Removes block placement delay."},
    {name:"Fly", category:"Movement", description: "Enables creative-like flight in survival mode."},
    {name:"FocusFps", category:"Render", description: "Reduces rendering when the game is unfocused."},
    {name:"Freecam", category:"Movement", description: "Detaches camera from player for free exploration."},
    {name:"Fullbright", category:"Render", description: "Removes darkness by maximizing brightness."},
    {name:"Glide", category:"Movement", description: "Slows falling speed for controlled descent."},
    {name:"GuiMove", category:"Movement", description: "Allows movement while GUIs are open."},
    {name:"HighJump", category:"Movement", description: "Increases jump height."},
    {name:"ItemESP", category:"Render", description: "Highlights dropped items through walls."},
    {name:"Jesus", category:"Movement", description: "Walk on water and lava surfaces."},
    {name:"Jetpack", category:"Movement", description: "Provides vertical flight with customizable speed."},
    {name:"KillAura", category:"Combat", description: "Automatically attacks nearby entities."},
    {name:"MaceAura", category:"Combat", description: "Automatically attacks using mace mechanics."},
    {name:"MCA", category:"Misc", description: "Automated middle-click action."},
    {name:"Nametags", category:"Combat", description: "Enhances nametags with additional information."},
    {name:"Noclip", category:"Movement", description: "Walk through solid blocks."},
    {name:"NoFall", category:"Movement", description: "Prevents fall damage."},
    {name:"NoJumpDelay", category:"Movement", description: "Removes delay between jumps."},
    {name:"NoRender", category:"Render", description: "Disables rendering of specific game elements."},
    {name:"NoSlowdown", category:"Movement", description: "Prevents slowdown from soul sand, items, etc."},
    {name:"Nuker", category:"World", description: "Breaks multiple blocks simultaneously."},
    {name:"PlayerESP", category:"Render", description: "Highlights players through walls."},
    {name:"POV", category:"Render", description: "View another player or mob's point of view."},
    {name:"RandomPlace", category:"Misc", description: "Places blocks in random positions."},
    {name:"Reach", category:"Combat", description: "Increases reach distance for blocks and entities."},
    {name:"ReverseStep", category:"Movement", description: "Instantly descend full blocks."},
    {name:"Safewalk", category:"Movement", description: "Prevents falling off edges."},
    {name:"Scaffold", category:"World", description: "Automatically places blocks beneath you while walking."},
    {name:"Sneak", category:"Movement", description: "Toggles sneaking for safe edge building."},
    {name:"Speed", category:"Movement", description: "Increases movement speed."},
    {name:"Spider", category:"Movement", description: "Climb walls like a spider."},
    {name:"Sprint", category:"Movement", description: "Automatically sprints when moving forward."},
    {name:"Step", category:"Movement", description: "Steps up full blocks without jumping."},
    {name:"Strafe", category:"Movement", description: "Maintains momentum while strafing."},
    {name:"Surround", category:"World", description: "Places blocks around player for protection."},
    {name:"TileBreaker", category:"World", description: "Breaks specified tile entities in range."},
    {name:"Timer", category:"Misc", description: "Modifies game tick speed."},
    {name:"Tooltips", category:"Render", description: "Enhances item tooltips with additional information."},
    {name:"Tracer", category:"Render", description: "Draws lines to entities for tracking."},
    {name:"Trajectory", category:"Render", description: "Shows predicted path of projectiles."},
    {name:"TriggerBot", category:"Combat", description: "Attacks entities when crosshair is over them."},
    {name:"XCarry", category:"Misc", description: "Allows carrying items in crafting grid slots."},
    {name:"XRay", category:"Render", description: "Makes selected blocks visible through walls."},
    {name:"Zoom", category:"Render", description: "Provides adjustable zoom function."},
];
export default Hacks;
