export enum Category{

}

export type Hack = {
    name: string,
    category : string,
    description: string,
}

export const Hacks : Hack[] = [
    {name:"Aimbot", category:"Combat", description: "Automatically aims at nearby entities. Configurable targeting options and rotation settings."},
    {name:"AntiCactus", category:"Misc", description: "Prevents damage from cacti by treating them as non-solid blocks."},
    {name:"AntiInvis", category:"Combat", description: "Reveals invisible players and entities by forcing their render state."},
    {name:"AntiKnockback", category:"Combat", description: "Reduces or eliminates knockback from attacks and explosions."},
    {name:"AutoEat", category:"Misc", description: "Automatically consumes food when hunger is low. Configurable thresholds."},
    {name:"AutoFarm", category:"World", description: "Automatically harvests and replants crops in range. Works with various crop types."},
    {name:"AutoFish", category:"Misc", description: "Automates fishing by detecting and reeling in catches. Anti-AFK compatible."},
    {name:"AutoSign", category:"World", description: "Automatically writes configurable text on signs when placed."},
    {name:"AutoSoup", category:"Combat", description: "Automatically consumes soup for quick health regeneration in PvP."},
    {name:"AutoTotem", category:"Combat", description: "Automatically equips totems of undying from inventory to offhand."},
    {name:"AutoRespawn", category:"Combat", description: "Instantly respawns player upon death without death screen."},
    {name:"AutoWalk", category:"Movement", description: "Automatically walks in specified direction. Customizable path options."},
    {name:"BedAura", category:"Combat", description: "Automatically breaks nearby beds."},
    {name:"BowAimbot", category:"Combat", description: "Automatically aims at a target based off of projectile velocity."},
    {name:"Breadcrumbs", category:"Render", description: "Renders a trail showing your movement path. Useful for navigation."},
    {name:"ChestESP", category:"Render", description: "Highlights storage containers through walls. Different colors for different types."},
    {name:"Criticals", category:"Combat", description: "Forces critical hits on every attack without jumping."},
    {name:"CrystalAura", category:"Combat", description: "Automatically places and detonates end crystals for PvP."},
    {name:"EntityESP", category:"Render", description: "Highlights all entities through walls with customizable colors."},
    {name:"FastPlace", category:"Misc", description: "Removes block placement delay for rapid building."},
    {name:"FastBreak", category:"Misc", description: "Increases block breaking speed significantly."},
    {name:"Fly", category:"Movement", description: "Enables creative-like flight in survival mode. Multiple modes available."},
    {name:"Freecam", category:"Freecam", description: "Detaches camera from player body for free exploration."}, 
    {name:"Fullbright", category:"Render", description: "Removes darkness by maximizing gamma/brightness."},
    {name:"ItemESP", category:"Render", description: "Highlights dropped items through walls."},
    {name:"Glide", category:"Movement", description: "Slows falling speed for controlled descent."},
    {name:"Jesus", category:"Movement", description: "Allows walking on water and lava surfaces."},
    {name:"Jetpack", category:"Movement", description: "Provides vertical flight with customizable speed."},
    {name:"KillAura", category:"Combat", description: "Automatically attacks nearby entities within range."},
    {name:"Nametags", category:"Combat", description: "Enhances player nametags with additional information."},
    {name:"Noclip", category:"Movement", description: "Allows walking through solid blocks."},
    {name:"NoFall", category:"Movement", description: "Prevents fall damage completely."},
    {name:"NoJumpDelay", category:"Movement", description: "Removes delay between jumps."},
    {name:"NoOverlay", category:"Render", description: "Removes screen overlays like fire, water, and pumpkin."},
    {name:"NoSlowdown", category:"Movement", description: "Prevents slowdown from soul sand, using items, etc."},
    {name:"Nuker", category:"World", description: "Breaks multiple blocks simultaneously in radius."},
    {name:"PlayerESP", category:"Render", description: "Highlights players through walls with customizable options."},
    {name:"POV", category:"Render", description: "Allows you to view another player or mob's point of view (POV)."},
    {name:"Reach", category:"Render", description: "Increases player reach distance for blocks and entities."},
    {name:"Safewalk", category:"Movement", description: "Prevents falling off edges while walking."},
    {name:"Sneak", category:"Movement", description: "Toggles sneaking state for building on edges safely."},
    {name:"SpawnerESP", category:"Render", description: "Highlights mob spawners through walls."},
    {name:"Spider", category:"Movement", description: "Allows climbing walls like a spider."},
    {name:"Sprint", category:"Movement", description: "Automatically sprints when moving forward."},
    {name:"Step", category:"Movement", description: "Automatically steps up full blocks without jumping."},
    {name:"Surround", category:"World", description: "Automatically places blocks around player for protection."},
    {name:"TileBreaker", category:"World", description: "Automatically breaks specified tile entities in range."},
    {name:"Timer", category:"Misc", description: "Modifies game tick speed for faster actions."},
    {name:"Tracer", category:"Render", description: "Draws lines to entities for easy tracking."},
    {name:"Trajectory", category:"Render", description: "Shows predicted path of arrows and throwables."},
    {name:"TriggerBot", category:"Combat", description: "Automatically attacks entities when crosshair is over them."},
    {name:"XRay", category:"Render", description: "Makes selected blocks visible through walls for easy ore finding."},
    {name:"Zoom", category:"Render", description: "Provides adjustable zoom function like optifine."},
];
export default Hacks;